import Mascot from '../assets/images/mascot.png'
import ustp from '../assets/images/ustp.png'
import email from '../assets/GIF/maildelivery.gif'
import sadboi from '../assets/images/sadboi.png'
import Pomo from '../assets/images/pomo.jpeg'
import QrCode from '../assets/images/qrCode.png'
import Loader from '../assets/GIF/loader.gif'
import pomoMethod from '../assets/images/pomomethod.jpg'
import quick from '../assets/images/quick.png'
import Badge1 from '../assets/Badges/badgesImage/badge1.png'
import Badge2 from '../assets/Badges/badgesImage/badge2.png'
import Badge3 from '../assets/Badges/badgesImage/badge3.png'
import Badge4 from '../assets/Badges/badgesImage/badge4.png'
import Badge5 from '../assets/Badges/badgesImage/badge5.png'
import Badge6 from '../assets/Badges/badgesImage/badge6.png'
import Badge7 from '../assets/Badges/badgesImage/badge7.png'
import Badge8 from '../assets/Badges/badgesImage/badge8.png'
import logo from '../assets/images/icon.png'

export default {Mascot, ustp, email, sadboi, logo, Pomo, QrCode,Loader, pomoMethod, quick, Badge1, Badge4, Badge2, Badge3,Badge5, Badge6, Badge7, Badge8
}